### ISSUE TITLE
This URL fails (parentheses? spaces?)

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifarchive-unbox#10]
https://unbox.ifarchive.org/?url=http://ifarchive.org/if-archive/games/competition2020/Games/Jay%20Schillings%20Edge%20of%20Chaos/Chaos%20%28Offline%20Play%29.zip

> Error: Command failed: curl https://ifarchive.org/if-archive/games/competition2020/Games/Jay Schillings Edge of Chaos/Chaos (Offline Play).zip -o /home/data/cache/8yypxconu.zip -s -S -D -
curl: (3) URL using bad/illegal format or missing URL

**Comment by curiousdannii** [comment]
Probably the parentheses, spaces have been fine before.
