### ISSUE TITLE
Support .tgz

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifarchive-unbox#20]
And any other prevalent compressed files in the archive?

**Comment by erkyrath** [comment]
Now that I think about it, `.tar.Z` is moderately common for files from the early 90s.

I think all other compression formats are old platform-specific ones like .sit, .sea, .hqx, .bin (classic MacOS). Not a priority.

**Comment by curiousdannii** [comment]
Closed by #29
