### ISSUE TITLE
Add script to purge file from cache

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifarchive-unbox#21]
Make a CLI script that
1. gets the list of individual file URLs
2. shuts down the docker containers
3. purges the local cache entries (for both the app and nginx)
4. asks cloudflare to purge its cache
5. starts the containers

**Comment by curiousdannii** [comment]
@erkyrath This would be used so rarely (if ever) that I wonder if we could make it simply empty all of the caches, rather than purging specific files? Would make it quite a bit simpler.

**Comment by erkyrath** [comment]
Would you have to bring down the containers before deleting those folders and then bring them back up?

**Comment by curiousdannii** [comment]
Yes, either way the app needs to be restarted because it's not designed for things in the file cache to disappear. We could delete a single file from the file cache, that's easy. The Nginx cache uses hashes so I don't think it's really very possible to just delete some of it. And the Cloudflare cache... well the API might not be very complex, but it will be more complex than pushing the button in the control panel!

**Comment by erkyrath** [comment]
Ok, we can just document the sequence "stop app, delete stuff, restart app".

This is also what you need to update the config file or the app source, as I understand it.
