### ISSUE TITLE
Tar and unzip seem to fail sometimes

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifarchive-unbox#38]
list_contents() is failing on some files. Examples that I see:

[infocom/compilers/inform6/library/old/inform_library61.tar.gz][inform_library61.tar.gz]

> Error: tar error: tar: A lone zero block at 533

[games/pc/hallowee.zip][hallowee.zip]

> Error: Command failed: unzip -Z1 /home/data/cache/2obskzspcc.zip warning [/home/data/cache/2obskzspcc.zip]: 128 extra bytes at beginning or within zipfile (attempting to process anyway)

[inform_library61.tar.gz]: https://unbox.ifarchive.org/?url=%2Fif-archive%2Finfocom%2Fcompilers%2Finform6%2Flibrary%2Fold%2Finform_library61.tar.gz
[hallowee.zip]: https://unbox.ifarchive.org/?url=%2Fif-archive%2Fgames%2Fpc%2Fhallowee.zip

In both cases, messages appear on stderr but the files unpack correctly anyhow.

I think the correct path is to rely on the exit status rather than stderr. Messages on stderr should be logged, but should not throw errors.

There's a nuisance factor in that tar's exit status is 0 for success, 1 for error. unzip has a big list of exit statuses (see man page); it boils down to 0 for success, 1 for success-with-warnings, higher values for error. So we have to check those values separately for tar vs unzip.

**Comment by curiousdannii** [comment]
Thanks for the diagnosis, that all sounds reasonable. I'll try to take a look at it this week.

**Comment by curiousdannii** [comment]
Fixed by #41.
