### ISSUE TITLE
Tar paths starting with ./ confuse the app

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifarchive-unbox#40]
Depending on how a tar file was created, the `tar -tf` output might look like

```
./README.txt
./image.jpeg
```

list_contents() has no problem with this, and the index page gets generated with links to `/HASH/./README.txt` etc. However, because of browser URL resolution, when the user clicks on the link, the request comes in as `/HASH/README.txt`. The contents list does not contain `README.txt` so we return an error.

I can see a couple of ways to deal with this:

- list_contents() could strip initial `./` off the path.
- When looking up the file (the `details.contents.indexOf(file_path)` call in app.js), we could do a fallback check for `'./'+file_path` if the first lookup fails.

(This is a rare problem -- low priority. I first noticed it with http://ifarchive.org/if-archive/games/pc/mansion-19.2.tar.gz . That was when testing my fix for https://github.com/iftechfoundation/ifarchive-unbox/issues/38 , so you won't be able to observe this until that fix it in. I haven't hunted for other cases.)

**Comment by curiousdannii** [comment]
list_contents() should definitely normalise paths. If we do that I'm not sure if anything else would be required.
