### ISSUE TITLE
Rewrite links in HTML

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifarchive-unbox#45]
We can't catch everything so server redirects are still essential, but we can't rewrite basic HTML links, script inclusions, image sources, etc, so that they point to the main domain not the subdomain.

**Comment by erkyrath** [comment]
I dunno... this seems like it has a lot of ways to go subtly wrong, and the only benefit is a small improvement to loading time.

**Comment by curiousdannii** [comment]
Old HTML files like this should work now (once the Cloudflare cache expires): https://23trpo9d1a.unbox.ifarchive.org/23trpo9d1a/SHERLOCK.HTM

**Comment by curiousdannii** [comment]
Redirecting works adequately so I'll drop the idea of rewriting the HTML.
