### ISSUE TITLE
HTML fragments displayed as plain text

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifarchive-unbox#46]
Invalid HTML documents like the following currently receive a text/plain mime type. There's probably no harm to set them to text/html.

https://09rayftnzc.unbox.ifarchive.org/09rayftnzc/extras/The%20Bones%20of%20Rosalinda%20Hints%20and%20Walkthrough.html

**Comment by erkyrath** [comment]
Plan is to force any file whose suffix is .htm or .html (case-insensitive) to be text/html.

Repeating from chat:

> Well we still need /bin/file to detect the charset. But I guess we could overwrite the mimetype back to html and leave the charset...
