### ISSUE TITLE
Failure if path in the zip to be opened contains a space

### ISSUE THREAD

**Issue by DavidKinder** [iftechfoundation/ifarchive-unbox#49]
For the file [https://ifarchive.org/if-archive/games/twine/Paintball_Wizard.zip](https://ifarchive.org/if-archive/games/twine/Paintball_Wizard.zip) the main HTML file inside it is "Paintball Wizard/info.html". But the link

[https://unbox.ifarchive.org/?url=https://ifarchive.org/if-archive/games/twine/Paintball_Wizard.zip&open=Paintball%20Wizard/info.html](https://unbox.ifarchive.org/?url=https://ifarchive.org/if-archive/games/twine/Paintball_Wizard.zip&open=Paintball%20Wizard/info.html)

fails with "NotFoundError: Unknown file: https://ifarchive.org/if-archive/games/twine/Paintball_Wizard.zip". Interestingly, the link

[https://unbox.ifarchive.org/?url=https://ifarchive.org/if-archive/games/twine/Paintball_Wizard.zip&open=info.html](https://unbox.ifarchive.org/?url=https://ifarchive.org/if-archive/games/twine/Paintball_Wizard.zip&open=info.html)

does work.

**Comment by curiousdannii** [comment]
I don't think there's an issue with spaces, if it was the error would be something like

> NotFoundError: games/twine/Paintball_Wizard.zip does not contain file Paintball Wizard/info.html

The Unknown file error means it doesn't know about the .zip at all. So it's just a caching error. Which will be reduced now that the archive is checked every 5 minutes.
