### ISSUE TITLE
Way to indicate that Master-Index.xml has changed

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifarchive-unbox#51]
Having thought about https://github.com/iftechfoundation/ifarchive-unbox/pull/48 for a while, I think it *is* worth having a way for the Archive to push a "please refetch" message to Unbox.

This will make life easier for the volunteers; they won't have to think about a five-minute polling delay.

I don't think this has to involve cache headers at all. Just a request we can make that triggers check_for_update() immediately. (The request doesn't have to wait for check_for_update() to finish though.)

I want at least a little bit of mischief protection, so this request should be a POST with a shared secret key in the form field. On the Archive side this will be launched from `curl` or `wget` running as root, immediately after a new Master-Index.xml is written.

**Comment by curiousdannii** [comment]
Yep, makes sense

**Comment by erkyrath** [comment]
See here: https://github.com/iftechfoundation/ifarchive-ifmap-py/commit/76cc7e8dbbc3c46097d87fa7658f91bfd9a253a5
