### ISSUE TITLE
Incorrect index links to files whose names contain `#`

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifarchive-unbox#52]
https://unbox.ifarchive.org/?url=/if-archive/games/pc/spanish/zoo.zip

This zip file contains files where the name contains `#`, e.g. `M#ROCKY.1`.

To repro: Go to https://unbox.ifarchive.org/?url=/if-archive/games/pc/spanish/zoo.zip and click on the link to `M#ROCKY.1`

Actual: The link points to https://unbox.ifarchive.org/0impc5w62r/M#ROCKY.1 i.e. https://unbox.ifarchive.org/0impc5w62r/M with a "fragment identifier" of `#ROCKY.1`

Expected: https://unbox.ifarchive.org/?url=/if-archive/games/pc/spanish/zoo.zip should link to https://unbox.ifarchive.org/0impc5w62r/M%23ROCKY.1 (which _does_ work)

**Comment by curiousdannii** [comment]
Oops!

This should be fixed now, though the cache is still showing the error pages. I don't know if the IFArchive admin uncache button affects the individual unboxer file pages or not. But in any case, error pages should now only be cached up to one day.

**Comment by erkyrath** [comment]
I bounced the cache for that file.
