### ISSUE TITLE
open= should match an exact file name before looking in subfolders etc

### ISSUE THREAD

**Issue by curiousdannii** [iftechfoundation/ifarchive-unbox#53]
From slack:

> Hmm. This [Ishmael.zip](https://unbox.ifarchive.org/?url=/if-archive/games/springthing/2017/Ishmael.zip) has two index.html at different levels, the top-level one of which is what you want to launch the game. But doing the obvious thing in IFDB causes Unbox to [say](https://unbox.ifarchive.org/?url=https://ifarchive.org/if-archive/games/springthing/2017/Ishmael.zip&open=index.html) "BadRequestError: Filename is not unique".
Is there a way round this, with the things that you can do in an IFDB record? I didn't see one reading the [unbox spec](https://github.com/iftechfoundation/ifarchive-unbox/blob/main/doc/spec.md).

**Comment by erkyrath** [comment]
I like the idea of a "this is the file in the zip to launch" metadata line. Unless that's already supported, in which case we just have to document it on the ifarchive side!

`unbox-startfile` or something.

**Comment by curiousdannii** [comment]
The main issue is with IFDB, where we can't really know if it's an accurate filename or not. I think that looking for an exact match and then following the current heuristics should still be a good design though.

If the IFArchive has an accurate filename to launch it could just create the final URL itself...
