### ISSUE TITLE
Apostrophe in file name causes broken links

### ISSUE THREAD

**Issue by Keltena** [iftechfoundation/ifarchive-unbox#55]
See: https://unbox.ifarchive.org/?url=/if-archive/games/ink/A%20Woman%27s%20Duty.zip

"View contents" works, but the links all point to `A Woman&#39;s Duty` (nonexistent) rather than `A Woman's Duty` (correct).

For example, opening index.html gives me https://26kcyupiop.unbox.ifarchive.org/26kcyupiop/A%20Woman&%2339;s%20Duty/index.html?
The actual file is at https://26kcyupiop.unbox.ifarchive.org/26kcyupiop/A%20Woman%27s%20Duty/index.html?

**Comment by erkyrath** [comment]
Same issue as https://github.com/iftechfoundation/ifarchive-unbox/issues/39 .

**Comment by curiousdannii** [comment]
I don't think it's the same, this one looks like it's being double encoded, whereas that one was a quirky of the actual zip program. So this one should be quick to fix.

**Comment by curiousdannii** [comment]
Fixed, though you'll need to bust the cache for that zip index.
