### ISSUE TITLE
Wrong Content-Type for https://unbox.ifarchive.org/12f7pvz4p1/MAG09.TXT

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifarchive-unbox#56]
```
$ curl --head https://unbox.ifarchive.org/12f7pvz4p1/MAG09.TXT
HTTP/2 200
date: Tue, 28 May 2024 20:59:38 GMT
content-type: application/octet-stream; charset=binary
access-control-allow-origin: *
cache-control: max-age=604800, no-transform
last-modified: Sat, 11 Jan 1997 05:00:00 GMT
cf-cache-status: HIT
age: 646
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=pZO8BKsttX8OzwwGmO0szUbZ6DMkp0baXKUB7H1%2Bwx42kBXOW2Yg3yKNckTendPTCKY%2Fv5m3pCQvEvnrGhZENSNGQz6F6hdOwo843HuFGQjbWNJ23J4%2FV3Ea7kcxlGjoZ%2FeYfoE%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 88b12b6d7c73f9ea-SJC
```

Actual: `content-type: application/octet-stream; charset=binary`
Expected: `content-type: text/plain` as it is for https://unbox.ifarchive.org/1ko9qk23m7/MAG08.TXT

**Comment by dfabulich** [comment]
I spent a minute digging into this. The code in question is the `set_type` function of `app.js`. https://github.com/iftechfoundation/ifarchive-unbox/blob/main/app/src/app.js#L384-L420

It does recognize that `.txt` means `text/plain` in https://github.com/iftechfoundation/ifarchive-unbox/blob/main/app/src/common.js#L37 but it also identifies `text/plain` as a "type to detect better" in https://github.com/iftechfoundation/ifarchive-unbox/blob/main/app/src/common.js#L128-L132

The way it does that "better" detection is by running the [`file`](https://man7.org/linux/man-pages/man1/file.1.html) command on the file. And, sure enough:

```
$ file MAG09.TXT
MAG09.TXT: data
$ file MAG08.TXT
MAG08.TXT: ISO-8859 text, with CRLF line terminators
```

I believe `file` is saying this because the file is using the IBM437 charset at line 224.

```
    My adress is:
                 Praceta Carlos Manito Torres, nº4/6ºC
                 2900 Setúbal
                 Portugal
```

I can see three options here:
1. Find and fix this bug in `file` (… that sounds _really_ hard!)
2. Add a way to hard-code known `file` errors, so we could correctly mark the file as `text/plain; charset=IBM437`
3. Ignore the bug

**Comment by curiousdannii** [comment]
What's the zip, and how important is it? I'd be inclined to just ignore it.

**Comment by dfabulich** [comment]
The zip is https://unbox.ifarchive.org/?url=/if-archive/magazines/TheMag/mag09.zip

Keltena reported the issue saying:

> Not that this is a world-ending problem; it just makes me curious what's going on.

It might make sense to ignore it for now, and add a facility to hard-code content types for certain files only if we see more issues like this crop up in the future.
