### ISSUE TITLE
IFDB Play On-line link gives "Unknown file" error for otherwise-working file

### ISSUE THREAD

**Issue by Keltena** [iftechfoundation/ifarchive-unbox#57]
The Play On-line button for [To Let Go](https://ifdb.org/viewgame?id=yeu9008q8hgnxyvt) leads to the following URL and error:
https://unbox.ifarchive.org/?url=https://www.ifarchive.org/if-archive/games/mini-comps/neo-twinyjam/2024/To%20let%20go.zip&open=To%20let%20go.html
`NotFoundError: Unknown file: https://www.ifarchive.org/if-archive/games/mini-comps/neo-twinyjam/2024/To let go.zip`

I don't get this error when I…
- Remove `www.` (or `https://www.ifarchive.org`) from the start of the file path: https://unbox.ifarchive.org/?url=https://ifarchive.org/if-archive/games/mini-comps/neo-twinyjam/2024/To%20let%20go.zip&open=To%20let%20go.html
- Remove `&open=` from the end (and then click the HTML file):
https://unbox.ifarchive.org/?url=https://www.ifarchive.org/if-archive/games/mini-comps/neo-twinyjam/2024/To%20let%20go.zip
- Go to the URL given in the error message: https://www.ifarchive.org/if-archive/games/mini-comps/neo-twinyjam/2024/To%20let%20go.zip

I haven't seen this issue with any other games. (For example, https://unbox.ifarchive.org/?url=https://www.ifarchive.org/if-archive/games/mini-comps/neo-twinyjam/2024/you%20are%20an%20ancient%20chinese%20poet%20in%20exile.zip&open=you%20are%20an%20ancient%20chinese%20poet%20in%20exile.html works fine.)

**Comment by curiousdannii** [comment]
Is that a brand new file? Could be a caching issue.

**Comment by Keltena** [comment]
It's a new file. Clearing the cache hasn't helped as far as I can tell.

**Comment by Keltena** [comment]
As of today or yesterday, the file works fine. I'm closing this and assuming it was some sort of caching issue(?), unless someone who knows better thinks otherwise.
